// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc3
// source: ESService.proto

package esPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ESService_GetFileHashList_FullMethodName = "/ESService.ESService/GetFileHashList"
)

// ESServiceClient is the client API for ESService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 下载服务定义（函数名与handler保持一致）
type ESServiceClient interface {
	// 获取文件 hash 列表
	GetFileHashList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
}

type eSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewESServiceClient(cc grpc.ClientConnInterface) ESServiceClient {
	return &eSServiceClient{cc}
}

func (c *eSServiceClient) GetFileHashList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, ESService_GetFileHashList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ESServiceServer is the server API for ESService service.
// All implementations must embed UnimplementedESServiceServer
// for forward compatibility.
//
// 下载服务定义（函数名与handler保持一致）
type ESServiceServer interface {
	// 获取文件 hash 列表
	GetFileHashList(context.Context, *SearchReq) (*SearchResp, error)
	mustEmbedUnimplementedESServiceServer()
}

// UnimplementedESServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedESServiceServer struct{}

func (UnimplementedESServiceServer) GetFileHashList(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileHashList not implemented")
}
func (UnimplementedESServiceServer) mustEmbedUnimplementedESServiceServer() {}
func (UnimplementedESServiceServer) testEmbeddedByValue()                   {}

// UnsafeESServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ESServiceServer will
// result in compilation errors.
type UnsafeESServiceServer interface {
	mustEmbedUnimplementedESServiceServer()
}

func RegisterESServiceServer(s grpc.ServiceRegistrar, srv ESServiceServer) {
	// If the following call pancis, it indicates UnimplementedESServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ESService_ServiceDesc, srv)
}

func _ESService_GetFileHashList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ESServiceServer).GetFileHashList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ESService_GetFileHashList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ESServiceServer).GetFileHashList(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ESService_ServiceDesc is the grpc.ServiceDesc for ESService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ESService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ESService.ESService",
	HandlerType: (*ESServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileHashList",
			Handler:    _ESService_GetFileHashList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ESService.proto",
}
